### ISSUE TITLE
Strap failed

### ISSUE THREAD

**Issue by pkrugdaptiv** [daptiv/strap#13]
Homebrew Bundle failed
Running with debug resulted in 'permission denied'

![screen shot 2018-07-09 at 1 14 45 pm](https://user-images.githubusercontent.com/37554360/42473739-47bb8da0-837a-11e8-8614-c8a3a33a39e8.png)

**Comment by dachew** [comment]
Run with `--debug` and post results here

**Comment by dachew** [comment]
Actually, @pkrugdaptiv email the log to @jtrinklein and @dachew

**Comment by jtrinklein** [comment]
resolved?
